type: "nodejs:10"

# The size of the persistent disk of the application (in MB).
disk: 2048

dependencies:
  nodejs:
    pm2: "^2.5.0"

web:
  commands:
    start: "PM2_HOME=/app/run pm2 start server.js --no-daemon"

hooks:
  build: |
    npm install
#    npm start